// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchedAppAPI.Models;

public partial class Activity
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public DateTime? starttime { get; set; }

    public DateTime? endtime { get; set; }

    public int userid { get; set; }

    public int? teamid { get; set; }

    public string location { get; set; }
}