// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchedAppAPI.Models;

public partial class Team
{
    public int id { get; set; }

    public int coachid { get; set; }

    public int sportid { get; set; }

    public string name { get; set; }
}