// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchedAppAPI.Models;

public partial class Team
{
    public int Id { get; set; }

    public string Sport { get; set; }

    public string CoachId { get; set; }
}