// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchedAppAPI.Models;

public partial class User
{
    public int id { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string firstname { get; set; }

    public string lastname { get; set; }

    public int? TeamId { get; set; }

    public int isCoach { get; set; }
}