// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchedAppAPI.Models;

public partial class User
{
    public int id { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }
}